## YAML Template.
---
spring:
  application.name: match-feed
  config.import: "optional:configserver:"
  cloud:
    config.uri: http://localhost:8888

---
spring:
  config.activate.on-profile: docker
  cloud.config.uri: http://config:8080
  
---
spring:
  config.activate.on-profile: test
  cloud.config.enabled: false
  datasource:
    url: jdbc:hsqldb:mem:testdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect

eureka.client.enabled: false

api:
  key:
    name: test
    value: test
  base-url: test
  endpoints:
    get-matches: test
    get-finished-matches: test
