## YAML Template.
---
spring:
  application.name: gateway
  config.import: "optional:configserver:"
  cloud.config.uri: http://localhost:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          #jwk-set-uri: http://localhost:9000/.well-known/openid-configuration

---
spring:
  config.activate.on-profile: docker
  cloud.config.uri: http://config:8080
