## YAML Template.
---
spring:
  application.name: scheduler
  config.import: "optional:configserver:"
  cloud:
    config.uri: http://localhost:8888
    function:
      definition: eventConsumer;
    stream:
      bindings:
        eventConsumer-in-0:
          destination: matchEvent
          content-type: application/json
        matchCompletion-out-0:
          destination: matchCompletion
          content-type: application/json

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          
logging:
  level:
    rs.ac.bg.fon.mas.scheduler: TRACE

---
spring:
  config.activate.on-profile: docker
  cloud.config.uri: http://config:8080
