## YAML Template.
---
spring:
  application.name: scheduler
  config.import: "optional:configserver:"
  cloud:
    config.uri: http://localhost:8888
    function:
      definition: eventConsumer;
    stream:
      bindings:
        eventConsumer-in-0:
          destination: matchEvent
          content-type: application/json

logging:
  level:
    rs.ac.bg.fon.mas.scheduler: TRACE

---
spring:
  config.activate.on-profile: docker
  cloud.config.uri: http://config:8080
  
---
spring:
  config.activate.on-profile: test
  cloud.config.enabled: false
  datasource:
    url: jdbc:hsqldb:mem:testdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect

eureka.client.enabled: false
