## YAML Template.
---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          #jwk-set-uri: http://localhost:9000/.well-known/openid-configuration
  cloud:
    stream:
      default-binder: kafka
      kafka.binder:
        brokers: localhost
        defaultBrokerPort: 9093

  kafka:
    host: localhost
    port: 9093

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/

---
spring:
  config.activate.on-profile: docker

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8080
          #jwk-set-uri: http://auth-server:9000/.well-known/openid-configuration
  cloud:
    stream:
      default-binder: kafka
      kafka.binder:
        brokers: kafka
        defaultBrokerPort: 9092

  kafka:
    host: kafka
    port: 9092

eureka:
  client:
    serviceUrl.defaultZone: http://discovery:8080/eureka/
