## YAML Template.
---
server:
  port: 81
  
spring:
  datasource:
    url: jdbc:mysql://localhost/schedulerdb
    port: '3306'
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: 'false'
  cloud:
    function:
      definition: eventConsumer;
    stream:
      bindings:
        eventConsumer-in-0:
          destination: matchEvent
          content-type: application/json
          group: scheduler
        matchCompletion-out-0:
          destination: matchCompletion
          content-type: application/json

logging:
  level:
    org.springframework: OFF
    org.apache.catalina: OFF
    org.apache.kafka: OFF
    org.hibernate: OFF
    com.zaxxer.hikari: OFF
    com.netflix.discovery: OFF
    rs.ac.bg.fon.mas.scheduler: OFF
    rs.ac.bg.fon.mas.scheduler.messaging.config: TRACE

---
spring:
  config.activate.on-profile: docker
  datasource:
    url: jdbc:mysql://schedulerdb/schedulerdb

server:
  port: 8080
