## YAML Template.
---
spring:
  application.name: ticketing
  config.import: "optional:configserver:"
  cloud:
    config.uri: http://localhost:8888
    function:
      definition: matchConsumer;
    stream:
      bindings:
        matchConsumer-in-0:
          destination: match
          content-type: application/json

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

api.scheduler.url: http://scheduler/matches/by-ids

---
spring:
  config.activate.on-profile: docker
  cloud.config.uri: http://config:8080
