## YAML Template.
---
services:
  zookeeper:
    container_name: "mstr-zookeeper"
    image: "wurstmeister/zookeeper:latest"
    ports:
    - "2181:2181"
  kafka:
    container_name: "mstr-kafka"
    depends_on:
      - zookeeper
    image: "wurstmeister/kafka:latest"
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_CREATE_TOPICS: "a2CreateRequest:1:1,a2CreateResponse:1:1,a2UpdateRequest:1:1,a2UpdateResponse:1:1,a2DeleteRequest:1:1,a2DeleteResponse:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  akhq:
    container_name: "mstr-akhq"
    depends_on:
      - kafka
    image: "tchiotludo/akhq:latest"
    ports:
      - 8081:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: 'kafka:9092' 
