## YAML Template.
---
spring:
  application.name: discovery
  config.import: "optional:configserver:"
  cloud.config.uri: http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config.activate.on-profile: docker
  cloud.config.uri: http://config:8080
